### PR TITLE
Rework the "backdrop blitting"

### LINKED ISSUE #9: Rework the "backdrop blitting"
Many MachGui controls for the menus depend on StartupScreens solely so they can call blitBackdrop. The method is invoked each frame to redraw a chunk of the menu bitmap before redrawing the control itself.

GuiRoot will be given the ability to have named bitmaps that can be used for the cut-and-paste stuff that's expected by the menu stuff. It will also manage these as well, instead of constantly reloading the background upon 'context change.' :)

#### Components to be modified:

- RenSurface (GuiBitmap), very minor tweaks
- GuiPainter will be coded to an interface, IGuiPainter.
- GuiRoot
- MachGuiStartupScreens
- MachGui*** Control classes that call blitBackdrop. **_Perhaps, only classes that only call blitBackdrop will be changed for now?_**

#### Enhancements / New Components:

- A new class to load bitmaps that need to be shared at the GuiRoot level. These bitmaps may be named by a key, e.g.: `"backdrop"` and used for shared blitting operations.
- Said class will enable you to perform the blits on named bitmaps
- GuiRoot will be composed of this new class

### PR DESCRIPTION
**Pull request by m-flak**
Closes #9 

This work will enable up-scaling of the in-game menus. It should now be possible to use a much larger image for menu backgrounds. However, the GUI won't be usable with a larger background image because the offsets of the controls are hardcoded everywhere.

### Issue description:

> Many MachGui controls for the menus depend on StartupScreens solely so they can call blitBackdrop. The method is invoked each frame to redraw a chunk of the menu bitmap before redrawing the control itself.
> 
> GuiRoot will be given the ability to have named bitmaps that can be used for the cut-and-paste stuff that's expected by the menu stuff. It will also manage these as well, instead of constantly reloading the background upon 'context change.' :)
> Components to be modified:
> 
>     RenSurface (GuiBitmap), very minor tweaks
>     GuiPainter will be coded to an interface, IGuiPainter.
>     GuiRoot
>     MachGuiStartupScreens
>     MachGui*** Control classes that call blitBackdrop. Perhaps, only classes that only call blitBackdrop will be changed for now?
> 
> Enhancements / New Components:
> 
>     A new class to load bitmaps that need to be shared at the GuiRoot level. These bitmaps may be named by a key, e.g.: "backdrop" and used for shared blitting operations.
>     Said class will enable you to perform the blits on named bitmaps
>     GuiRoot will be composed of this new class
> 
>

### CODE REVIEW

**Comment by Kaffeine** [comment]
I have those runtime warnings:
```
GuiRootSharedBitmaps::getNamedBitmap(): backdrop was never created!!!
GuiRootSharedBitmaps::blitNamedBitmap(): Attempted blit of null named bitmap.
```

Also, tests compilation fails with:
```
machines/test/gui/GuiRootSharedBitmapsTests.cpp:78:74: error: use of ‘auto’ in lambda
parameter declaration only available with ‘-std=c++14’
   78 |     sharedBitmaps.blitNamedBitmapFromArea(backdrop, srcBox, dstPoint, [](auto& src){
      |                                                                          ^~~~
```

IOW, this is a C++14 code: https://github.com/WiredForWar/machines/blob/5b892f6fbeb2393419c1ce8de94c96b31fec4c55/test/gui/GuiRootSharedBitmapsTests.cpp#L78

Probably you don't see this issue because you haven't pull CMake compatibility changes from `dev` (particularly [this](https://github.com/WiredForWar/machines/commit/98fa845e2261b7ba3a9ec07529222b825f622bf0) commit) (I think we want to make the game crossplatform; to do so, we need to avoid compiler-specific code).

**Comment by Kaffeine** [comment]
So, can you please:
- Rebase on the current `dev` (there is no conflict),
- Replace the `auto &`  with `const Gui::Box &`, and
- reply if the runtime warnings are legit and should be fixed?

**Comment by Kaffeine** [comment]
Or (if you agree) I can merge your PR and fix the compile-time issues in the merge commit. It won't take my time.

**Comment by m-flak** [comment]
Warning messages should be printed to cerr when the tests are run.

Yeah, go ahead and merge things.

**Comment by Kaffeine** [comment]
> Warning messages should be printed to cerr when the tests are run.

Hm, indeed. I have no idea how tests were triggered but it seems to be the case.

**Comment by Kaffeine** [comment]
Merged. Thanks, it is nice to have this refactor merged. :+1:

**Pull request merged**
