### PR TITLE
 Fix intro video background and maintain aspect ratios

### LINKED ISSUE #13: Fix intro video (cutscene) background
Updated by Matthew 09/15/2022
## Tasklist:

- [x] Add call to "clear" the framebuffer in between logo images & intro cutscene in MachGuiStartupScreens
- [x] Update framescaler to preserve aspect ratio when upscaling: <br> W = Screen width, 
CodeCogsEqn

## Issue:
Right now some spikes from the Charybdis logo are rendered behind. I think it is weird, and the background should be solid black.

image

### PR DESCRIPTION
**Pull request by m-flak**
Fixes #13

### CODE REVIEW

**Comment by Kaffeine** [comment]
Hello. The code fixes look great!
But as for the CMake changes, there are more user and developer friendly ways to expose such options.

From developer point of view, "positive" variables (and APIs) are easier to read and they never turns into double negation.
Namely, there is an opinion and guideline to avoid "disable", "without", and other similar names in favor of "enable", "with", etc.

On the other hand. As a user, I want to be able to:
1. Successfully configure and build the project in the current environment. If some dependency is presented — use it. If no — ignore is possible.
2. Force use of dependency. E.g. I want to have the cutscenes *scaled* so I want to have a configuration error if this feature can't be enabled. The worst case for a packager is to successfully build a package to later find out that some of dependency had a slightly lower version and a project feature was silently disabled.
3. Force an ignore of dependency. E.g. even if it is installed I want to build the project without this dependency (e.g. because I want to redistribute the package to other environments or just test the project in this particular configuration).

For the user we can provide a conventional on/off/auto tristate options.
I went ahead and implemented the suggested approach: https://github.com/WiredForWar/machines/commit/4f874dc4753913078e3d4ef3b508a6a8fc278719
In the top `CMakeLists.txt` we ('ll) have:

```diff
diff --git CMakeLists.txt CMakeLists.txt
index f29db80e..1e2d3504 100644
--- CMakeLists.txt
+++ CMakeLists.txt
@@ -71,6 +71,12 @@ set(CMAKE_MODULE_PATH "${machines_SOURCE_DIR}/cmake" ${CMAKE_MODULE_PATH})
 # Build targets should be placed in the root build directory
 set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR})
 
+include(Utils)
+
+# Options for optional libs
+option_on_off_auto(BUILD_WITH_SWSCALE "Build with SWScale support" "Auto")
+option_on_off_auto(BUILD_WITH_ALURE "Build with Alure support" "Auto")
+
 # 32 bit build configuration
 option(BUILD_32 "Builds 32 bit executable" OFF)
 # Include cmake directory with some additions
@@ -132,14 +138,12 @@ find_package(GLEW REQUIRED)
 find_package(OpenAL REQUIRED)
 include(EnsureOpenALTarget)
 
-find_package(Alure)
+find_optional_dependency(Alure)
+find_optional_dependency(SWScale)
+
 find_package(ENet REQUIRED)
 find_package(Freetype REQUIRED)
 
-find_package(SWScale)
-set(USE_SWSCALE ${SWScale_FOUND})
-set(USE_ALURE ${Alure_FOUND})
-
 if(NOT DEV_BUILD)
     add_definitions(-DNDEBUG)
     add_definitions(-DPRODUCTION)
```

The implemented code also provides nice comboboxes for CMake configurators:
image
It supports any boolean values, so the user can do any of:
```
-DBUILD_WITH_SWSCALE=1
-DBUILD_WITH_SWSCALE=YES
-DBUILD_WITH_SWSCALE=TRUE
-DBUILD_WITH_SWSCALE=ON
-DBUILD_WITH_SWSCALE=AUTO
-DBUILD_WITH_SWSCALE=FALSE
... etc
```

Would you mind to rebase the branch without the CMake changes?
Would you mind if I'll rebase your branch and merge it without [60b8b10](https://github.com/WiredForWar/machines/pull/21/commits/60b8b1098eaa917923d26329ad7e7ac057d12910)?

**Comment by m-flak** [comment]
@Kaffeine Got you covered

**Comment by Kaffeine** [comment]
Merged. Thanks! :+1:

**Comment by m-flak** [comment]
Thats great! Make it happen.

**Pull request merged**
