### PR TITLE
Add Linux native and Windows cross builds (mingw32/64)

### PR DESCRIPTION
**Pull request by Kaffeine**
The artifacts are not self-sufficient in terms of shared libraries:
- Linux binary works on my PC but I use a distribution based on Ubuntu-20.04. The portability of this one is out of scope of this PR
- Win32 binary requires the libraries from the 1.5 release archive.
- Win64 binary requires some (64 bit) `freetype.dll` which is missing.

Note: 32bit `freetype.dll` is included in the release archive but 64bit is missing. Maybe 1.5 version release binary has freetype statically linked in.
Note: SWScale is now optional and it is not used (yet) in Windows builds (because of missing library).
Note: It seems that GitHub duplicates the builds: one build set is triggered by push and another is triggered by PR. We might want to disable builds for branches except `dev` but I find it useful to have it this way for now (e.g. this way we can see the build status of WIP and/or personal branches before we open PRs).

The goal of this PR is to provide automatic builds for Win32. Other CI jobs are not directly useful for the users (yet).

### CODE REVIEW

**Comment by m-flak** [comment]
On windows swscale is part of ffmpeg, [see headers & linker files in the Files list](https://packages.msys2.org/package/mingw-w64-x86_64-ffmpeg).

**Comment by m-flak** [comment]
332a332
Some of the tests need the weak symbols to do stubbing. Looks like conditional preproc directives and the disabling of certain unit tests for windows builds will be needed.

**Comment by Kaffeine** [comment]
> On windows swscale is part of ffmpeg, [see headers & linker files in the Files list](https://packages.msys2.org/package/mingw-w64-x86_64-ffmpeg).

It seems that those packages are only for MSYS2 *windows* environment and not for cross-compilation: https://github.com/msys2/MINGW-packages/issues/6277

I also work on Conan-based MSVC native Windows build but it is not ready yet and it is going to take at least 15-20 hours of work.

**Comment by Kaffeine** [comment]
> [332a332](https://github.com/WiredForWar/machines/commit/332a332e9029d25907cc24f91af6e6e0724ff4c1) Some of the tests need the weak symbols to do stubbing.

> some

It seems that this one is not needed. It is not overloaded or I don't see how and where. Probably it was useful when the game required a CD to run. 
Note: the tests are passing at https://github.com/WiredForWar/machines/runs/7940053235?check_suite_focus=true

image

**Comment by m-flak** [comment]
Oh, I thought weak symbols weren't working at all. :sweat_smile:

**Review by m-flak — APPROVED** [review]

**Pull request merged**
